name: Deploy AlgoCratic Futures

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.11]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        cd projects/algocratic-futures/backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio
    
    - name: Run tests
      run: |
        cd projects/algocratic-futures/backend
        pytest tests/ -v
    
    - name: Check clearance system integrity
      run: |
        cd projects/algocratic-futures/backend
        python -c "from clearance_system import ClearanceLevel; assert ClearanceLevel.UV == 9"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        cd projects/algocratic-futures
        docker build -t algocratic-futures:latest .
    
    - name: Deploy to production
      run: |
        echo "Deployment would happen here"
        echo "Remember: The Algorithm is watching"